services:
  - type: web
    name: billassistant
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    buildPacks:
      - https://github.com/heroku/heroku-buildpack-apt
